version: '3'
services:
  db:
    image: mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
      - ./dump/moodle.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    restart: always
  moodle:
    build: .
    container_name: moodle
    ports:
      - "80:80"
    links:
      - db:database
    volumes:
      - ./data:/var/data
      - ./src:/var/www/html/src
    labels:
      cron.moodle.command: "/usr/local/bin/php /var/www/html/src/admin/cli/cron.php"
      cron.moodle.interval: "every minute"  
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    links:
      - db:database
    environment:
      PMA_HOST: database
  tasks:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: America/Sao_Paulo
      LABEL_NAMESPACE: cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
    db:
      driver: local